### ISSUE TITLE
Ключ

### ISSUE THREAD

**Issue by PuppyLo** [Ghost2911/evotor-stock-manager#1]
Невозможно импортировать следующий файл ключей: EvotorStockManager_TemporaryKey.pfx. Возможно, файл ключа защищен паролем. Чтобы устранить эту ошибку, повторите попытку импорта сертификата или вручную установите сертификат в поставщик CSP строгого имени с использованием следующего имени контейнера ключей: VS_KEY_4B0C4534D1BE9036	EvotorStockManager

**Comment by Ghost2911** [comment]
Настройки проекта -> Подписывание -> Убрать галочки
